name: Deploy spec

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v2-beta
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Commit Changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: "fixup: [spec] `npm run build`"
